[build.environment]
PYTHON_VERSION = "3.12"

[build]
  command = "pip install -r requirements.txt"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "python app.py"
  port = 5000
